/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactInquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const WebsiteRating = IDL.Record({
  'id' : IDL.Nat,
  'comment' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'rating' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const BusinessHours = IDL.Record({
  'hours' : IDL.Text,
  'days' : IDL.Text,
});
export const SiteContent = IDL.Record({
  'businessHours' : BusinessHours,
  'aboutHeading' : IDL.Text,
  'heroHeading' : IDL.Text,
  'servicesDescription' : IDL.Text,
  'servicesHeading' : IDL.Text,
  'contactSubheading' : IDL.Text,
  'contactHeading' : IDL.Text,
  'heroSubheading' : IDL.Text,
  'aboutDescription' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'getAllRatings' : IDL.Func([], [IDL.Vec(WebsiteRating)], ['query']),
  'getAverageRating' : IDL.Func([], [IDL.Opt(IDL.Float64)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInquiry' : IDL.Func([IDL.Nat], [IDL.Opt(ContactInquiry)], ['query']),
  'getRecentRatings' : IDL.Func([IDL.Nat], [IDL.Vec(WebsiteRating)], ['query']),
  'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRating' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'updateSiteContent' : IDL.Func([SiteContent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactInquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const WebsiteRating = IDL.Record({
    'id' : IDL.Nat,
    'comment' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'rating' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const BusinessHours = IDL.Record({ 'hours' : IDL.Text, 'days' : IDL.Text });
  const SiteContent = IDL.Record({
    'businessHours' : BusinessHours,
    'aboutHeading' : IDL.Text,
    'heroHeading' : IDL.Text,
    'servicesDescription' : IDL.Text,
    'servicesHeading' : IDL.Text,
    'contactSubheading' : IDL.Text,
    'contactHeading' : IDL.Text,
    'heroSubheading' : IDL.Text,
    'aboutDescription' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
    'getAllRatings' : IDL.Func([], [IDL.Vec(WebsiteRating)], ['query']),
    'getAverageRating' : IDL.Func([], [IDL.Opt(IDL.Float64)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInquiry' : IDL.Func([IDL.Nat], [IDL.Opt(ContactInquiry)], ['query']),
    'getRecentRatings' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(WebsiteRating)],
        ['query'],
      ),
    'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRating' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'updateSiteContent' : IDL.Func([SiteContent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };